# path:
#   raw_path : ./data/raw/
#   processed_path : ./data/processed/
#   files_path: ./research/files/

# model:
#   beta1: 0.5
#   beta2: 0.999
#   momentum: 0.9
#   step_size: 10
#   gamma: 0.5


# For notebook purposes

path:
  raw_path : ../../data/raw/
  processed_path : ../../data/processed/
  files_path: ../../research/files/

model:
  beta1: 0.5
  beta2: 0.999
  momentum: 0.9
  step_size: 10
  gamma: 0.5